[package]
name = "eth2-client"
version = "0.1.0"
authors = ["Aurora <hello@aurora.dev>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ethereum-types = { version = "0.14.1", features = ["rlp", "serialize"],  default-features = false }
eth-types =  { path = "../eth-types" }
eth2-utility =  { path = "../eth2-utility" }
tree_hash = { git = "https://github.com/aurora-is-near/lighthouse.git", rev = "a3bdff781e689b50150a8d6e202dc7eec8f69aca" }
merkle_proof = { git = "https://github.com/aurora-is-near/lighthouse.git", rev = "a3bdff781e689b50150a8d6e202dc7eec8f69aca" }
bls = { git = "https://github.com/aurora-is-near/lighthouse.git", optional = true, rev = "a3bdff781e689b50150a8d6e202dc7eec8f69aca", default-features = false, features = ["milagro"]}
admin-controlled =  { path = "../admin-controlled" }
near-sdk = "4.0.0"
borsh = "0.9.3"
bitvec = "1.0.0"

[dev-dependencies]
lazy_static = "1.4.0"
serde_json = "1.0"
hex = "0.4.0"
workspaces = "0.4.0"
near-units = "0.2.0"
tokio = { version = "1.18.1", features = ["full"] }
anyhow = "1.0"

[features]
default = ["logs"]
bls = ["dep:bls"]
logs = []
mainnet = []